seed: 123456789
device: cuda:0
val_size: 0.01
test_size: 0.02
mini_batch_size: 512
lr: 1.0e-4
weight_decay: 1.0e-6
val_patience: 50
val_tolerance: 1.0e-4
max_epochs: 60
validation_freq: 12
checkpoint_freq: 12000
algorithm: betae
leiden_resolution: 5.0e-3
loader_hpars:
  dataset_name: freebase
  simulated: false
  sample_source: smore
  sampler_hpars:
    query_structure:
      - 1p
      - 2p
      - 3p
      - 2i
      - 3i
      - 2i1p
      - 1p2i
      - 2d
      - 3d
      - 2d1p
      - 1p2b
      - 1p2d
    num_negative_samples: 128
    num_neighbours: 10
    random_walk_length: 10
    context_radius: 2
    pagerank_importances: true
    walks_relation_specific: true
embedder_hpars:
  embedding_dim: 400
link_ranker_hpars:
  algorithm: betae
embedding_loss_hpars:
  margin: 60.0
